---
- name: Install TSM Agent
  hosts: all
  gather_facts: yes

  pre_tasks:
    - name: Ensure facts
      setup:

  roles:
    - tsm_detect
    - tsm_packages
    - tsm_proxy
    - tsm_windows
    - tsm_linux
    - tsm_database
    - tsm_cleanup
