[linux]
app.elev1.local
#db01.elev1.local
#test-tsm.elev1.local

[windows]
msapp.elev1.local
#dc20.elev1.local
#dc21.elev1.local
#mssql.elev1.local

#[asa]
#10.231.9.77

#[asa:vars]
#ansible_user=alchr
#ansible_ssh_pass=Sandb0x2024
#ansible_connection=ansible.netcommon.network_cli
#ansible_network_os=cisco.asa.asa
#ansible_ssh_type=ssh
#ansible_ssh_common_args='-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o PreferredAuthentications=password -o PubkeyAuthentication=no'
