---
- name: Collect Windows services from all servers
  hosts: windows
  gather_facts: no

  tasks:
    - name: Get filtered services (DisplayName only)
      ansible.windows.win_shell: |
        Get-Service |
        Where-Object {
          $_.DisplayName -notmatch "_[a-z0-9]{6,}"
        } |
        Select-Object -ExpandProperty DisplayName |
        Sort-Object -Unique
      register: services

    - name: Store per-host service list
      set_fact:
        host_services: "{{ services.stdout_lines }}"


- name: Show services
  hosts: windows[0]
  gather_facts: no

  vars:
    action_map:
      "1": stopped
      "2": started
      "3": restarted

  tasks:
    - name: Build overview from all servers
      set_fact:
        overview: |
          {% for host in groups['windows'] %}
          {{ host }}:
          {% for svc in hostvars[host].host_services %}
          {{ svc }}
          {% endfor %}

          {% endfor %}

    - name: Print all services
      debug:
        msg: "{{ overview.split('\n') }}"

    - name: Services to manage
      pause:
        prompt: "Indtast services (xxx,yyy)"
      register: service_input

    - name: Ask action
      pause:
        prompt: "Hvad vil du?\n1 = Stop\n2 = Start\n3 = Genstart"
      register: action_input

    - name: Set selected values
      set_fact:
        selected_services: "{{ service_input.user_input.split(',') | map('trim') | list }}"
        desired_state: "{{ action_map[action_input.user_input] }}"


- name: Apply action to Windows services
  hosts: windows
  gather_facts: no

  tasks:
    - name: Run action on selected services
      ansible.windows.win_service:
        name: "{{ item }}"
        state: "{{ hostvars[groups['windows'][0]].desired_state }}"
      loop: "{{ hostvars[groups['windows'][0]].selected_services }}"
      ignore_errors: yes
