- name: Linux tasks
  block:

    - name: Download packages
      get_url:
        url: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
      loop: "{{ selected_packages }}"

    - name: Install DEB packages
      apt:
        deb: "/tmp/{{ item | basename }}"
      loop: "{{ selected_packages }}"
      when: ansible_os_family == "Debian"

    - name: Install RPM packages
      yum:
        name: "/tmp/{{ item | basename }}"
        state: present
      loop: "{{ selected_packages }}"
      when: ansible_os_family in ['RedHat','OracleLinux']

    - name: Restart TSM service (non-blocking)
      systemd:
        name: dsmcad
        state: restarted
      failed_when: false

  when: ansible_os_family != "Windows"
