---
- hosts: asa
  gather_facts: false
  connection: network_cli
  vars_files:
    - group_vars/asa/vault.yml

  collections:
    - cisco.asa

  tasks:
    - name: Show ACLs (rå CLI-output)
      cisco.asa.asa_command:
        commands:
          - show access-list
      register: cli_acl

    - name: Vis ACL-linjer
      debug:
        var: cli_acl.stdout_lines
