---
- hosts: asa
  gather_facts: false
  connection: network_cli

  collections:
    - cisco.asa

  tasks:
    - name: test_outside
      cisco.asa.asa_acls:
        config:
          acls:
            - name: test_outside
              acl_type: extended
              aces:
                - grant: permit
                  line: 1
                  protocol: tcp
                  protocol_options:
                    tcp: true
                  source:
                    object_group: Jumphost-11
                  destination:
                    address: 10.231.9.100
                    netmask: 255.255.255.255
                    port_protocol:
                      eq: 80
                  inactive: false

                - grant: permit
                  line: 2
                  protocol: tcp
                  protocol_options:
                    tcp: true
                  source:
                    object_group: Jumphost-11
                  destination:
                    address: 10.231.9.101
                    netmask: 255.255.255.255
                    port_protocol:
                      eq: 80
                  inactive: false
        state: merged

    - name: Ligger ACL på outside interfaces
      cisco.asa.asa_config:
        lines:
          - access-group test_outside in interface outside

