- name: Detect Oracle
  stat:
    path: /etc/oratab
  register: oratab
  when: ansible_os_family != "Windows"

- name: Detect MSSQL
  ansible.windows.win_service:
    name: MSSQLSERVER
  register: mssql
  ignore_errors: true
  when: ansible_os_family == "Windows"

- name: Set database type (CLEAN)
  set_fact:
    database: >-
      {{
        'mssql' if (ansible_os_family == 'Windows' and not mssql.failed | default(true)) else
        'oracle' if (oratab.stat.exists | default(false)) else
        'none'
      }}

- name: Debug
  debug:
    msg: "OS={{ ansible_os_family }} DB={{ database }}"
