- name: Set OS-specific packages
  set_fact:
    os_packages: >-
      {{
        tsm_packages.RedHat if ansible_os_family in ['RedHat','OracleLinux']
        else tsm_packages.Debian if ansible_os_family == 'Debian'
        else tsm_packages.Windows if ansible_os_family == 'Windows'
        else []
      }}

- name: Set DB packages
  set_fact:
    db_packages: >-
      {{
        mssql_packages if (ansible_os_family == 'Windows' and database == 'mssql')
        else oracle_packages if (database == 'oracle')
        else []
      }}

- name: Merge packages
  set_fact:
    selected_packages: "{{ os_packages + db_packages }}"

- name: Debug packages
  debug:
    var: selected_packages
